"""Chat completion service using LiteLLM. Auto-generated by ChimerAI CLI."""

import json
import time
import uuid
from typing import AsyncIterator, Optional
import litellm
from litellm import acompletion
import structlog

from models import (
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatCompletionChoice,
    ChatCompletionChunk,
    ChatCompletionChunkChoice,
    DeltaMessage,
    Usage,
    ChatMessage,
)
from config import settings
from provider_client import provider_client

logger = structlog.get_logger()

litellm.set_verbose = False
litellm.drop_params = True


class ChatService:
    """Service for handling chat completions using LiteLLM."""

    async def _resolve_provider_kwargs(
        self,
        provider_id: Optional[str] = None,
        model: Optional[str] = None,
    ) -> dict:
        kwargs: dict = {}

        if provider_id:
            provider = await provider_client.get_provider(provider_id)
            if provider:
                if provider.api_key:
                    kwargs["api_key"] = provider.api_key
                if provider.base_url:
                    kwargs["api_base"] = provider.base_url
                return kwargs

        if await provider_client.is_available():
            default = await provider_client.get_default_provider()
            if default and default.api_key:
                kwargs["api_key"] = default.api_key
                if default.base_url:
                    kwargs["api_base"] = default.base_url
                return kwargs

        return kwargs

    async def create_completion(
        self,
        request: ChatCompletionRequest,
        provider_id: Optional[str] = None,
        user_id: Optional[str] = None,
    ) -> ChatCompletionResponse:
        logger.info("chat_completion_request", model=request.model, stream=False)

        try:
            provider_kwargs = await self._resolve_provider_kwargs(
                provider_id=provider_id, model=request.model,
            )

            messages = [
                {"role": msg.role.value, "content": msg.content}
                for msg in request.messages
            ]

            response = await acompletion(
                model=request.model,
                messages=messages,
                temperature=request.temperature,
                max_tokens=request.max_tokens,
                top_p=request.top_p,
                frequency_penalty=request.frequency_penalty,
                presence_penalty=request.presence_penalty,
                user=request.user,
                stream=False,
                **provider_kwargs,
            )

            result = ChatCompletionResponse(
                id=response.id or f"chatcmpl-{uuid.uuid4().hex[:8]}",
                object="chat.completion",
                created=int(time.time()),
                model=response.model,
                choices=[
                    ChatCompletionChoice(
                        index=choice.index,
                        message=ChatMessage(
                            role=choice.message.role,
                            content=choice.message.content or "",
                        ),
                        finish_reason=choice.finish_reason or "stop",
                    )
                    for choice in response.choices
                ],
                usage=Usage(
                    prompt_tokens=response.usage.prompt_tokens,
                    completion_tokens=response.usage.completion_tokens,
                    total_tokens=response.usage.total_tokens,
                ),
            )

            if provider_id and user_id:
                await provider_client.report_usage(
                    provider_id=provider_id,
                    user_id=user_id,
                    model=request.model,
                    prompt_tokens=response.usage.prompt_tokens,
                    completion_tokens=response.usage.completion_tokens,
                    endpoint="/api/chat",
                )

            return result

        except Exception as e:
            logger.error("chat_completion_error", error=str(e))
            raise

    async def create_streaming_completion(
        self,
        request: ChatCompletionRequest,
        provider_id: Optional[str] = None,
        user_id: Optional[str] = None,
    ) -> AsyncIterator[str]:
        logger.info("chat_completion_request", model=request.model, stream=True)

        try:
            provider_kwargs = await self._resolve_provider_kwargs(
                provider_id=provider_id, model=request.model,
            )

            messages = [
                {"role": msg.role.value, "content": msg.content}
                for msg in request.messages
            ]

            response = await acompletion(
                model=request.model,
                messages=messages,
                temperature=request.temperature,
                max_tokens=request.max_tokens,
                top_p=request.top_p,
                frequency_penalty=request.frequency_penalty,
                presence_penalty=request.presence_penalty,
                user=request.user,
                stream=True,
                **provider_kwargs,
            )

            total_prompt_tokens = 0
            total_completion_tokens = 0

            async for chunk in response:
                if not chunk.choices:
                    continue

                choice = chunk.choices[0]

                if hasattr(chunk, "usage") and chunk.usage:
                    total_prompt_tokens = getattr(chunk.usage, "prompt_tokens", 0) or 0
                    total_completion_tokens = getattr(chunk.usage, "completion_tokens", 0) or 0

                chunk_response = ChatCompletionChunk(
                    id=chunk.id or f"chatcmpl-{uuid.uuid4().hex[:8]}",
                    object="chat.completion.chunk",
                    created=int(time.time()),
                    model=chunk.model,
                    choices=[
                        ChatCompletionChunkChoice(
                            index=choice.index,
                            delta=DeltaMessage(
                                role=getattr(choice.delta, "role", None),
                                content=getattr(choice.delta, "content", None),
                            ),
                            finish_reason=choice.finish_reason,
                        )
                    ],
                )

                yield f"data: {chunk_response.model_dump_json()}\n\n"

            if provider_id and user_id and (total_prompt_tokens or total_completion_tokens):
                await provider_client.report_usage(
                    provider_id=provider_id,
                    user_id=user_id,
                    model=request.model,
                    prompt_tokens=total_prompt_tokens,
                    completion_tokens=total_completion_tokens,
                    endpoint="/api/chat/stream",
                )

            yield "data: [DONE]\n\n"

        except Exception as e:
            logger.error("streaming_completion_error", error=str(e))
            error_payload = json.dumps({"error": {"message": str(e), "type": "server_error"}})
            yield f"data: {error_payload}\n\n"
            yield "data: [DONE]\n\n"


chat_service = ChatService()
