"""Embedding generation service using LiteLLM. Auto-generated by ChimerAI CLI."""

from typing import Optional
from litellm import aembedding
import structlog

from models import (
    EmbeddingRequest,
    EmbeddingResponse,
    EmbeddingData,
    EmbeddingUsage,
)
from config import settings
from provider_client import provider_client

logger = structlog.get_logger()


class EmbeddingService:
    """Service for generating embeddings using LiteLLM."""

    async def _resolve_provider_kwargs(self, provider_id: Optional[str] = None) -> dict:
        kwargs: dict = {}

        if provider_id:
            provider = await provider_client.get_provider(provider_id)
            if provider:
                if provider.api_key:
                    kwargs["api_key"] = provider.api_key
                if provider.base_url:
                    kwargs["api_base"] = provider.base_url
                return kwargs

        if await provider_client.is_available():
            default = await provider_client.get_default_provider()
            if default and default.api_key:
                kwargs["api_key"] = default.api_key
                if default.base_url:
                    kwargs["api_base"] = default.base_url
                return kwargs

        return kwargs

    async def create_embeddings(
        self,
        request: EmbeddingRequest,
        provider_id: Optional[str] = None,
        user_id: Optional[str] = None,
    ) -> EmbeddingResponse:
        logger.info("embedding_request", model=request.model)

        try:
            provider_kwargs = await self._resolve_provider_kwargs(provider_id=provider_id)

            if isinstance(request.input, str):
                inputs = [request.input]
            else:
                inputs = request.input

            response = await aembedding(
                model=request.model,
                input=inputs,
                user=request.user,
                **provider_kwargs,
            )

            embeddings_data = [
                EmbeddingData(
                    object="embedding",
                    embedding=emb.embedding if hasattr(emb, "embedding") else emb["embedding"],
                    index=i,
                )
                for i, emb in enumerate(response.data)
            ]

            result = EmbeddingResponse(
                object="list",
                data=embeddings_data,
                model=response.model,
                usage=EmbeddingUsage(
                    prompt_tokens=response.usage.prompt_tokens,
                    total_tokens=response.usage.total_tokens,
                ),
            )

            if provider_id and user_id:
                await provider_client.report_usage(
                    provider_id=provider_id,
                    user_id=user_id,
                    model=request.model,
                    prompt_tokens=response.usage.prompt_tokens,
                    completion_tokens=0,
                    endpoint="/api/embeddings",
                )

            return result

        except Exception as e:
            logger.error("embedding_error", error=str(e))
            raise


embedding_service = EmbeddingService()
