"""File text extraction for RAG uploads. Auto-generated by ChimerAI CLI.

Supported formats:
- .txt, .md, .csv, .json, .log — plain text (UTF-8)
- .pdf — via PyMuPDF (pymupdf)
- .docx — via python-docx
"""

import io
import structlog
from pathlib import Path

logger = structlog.get_logger()

# Optional imports — graceful fallback
try:
    import fitz  # pymupdf
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False
    logger.warning("pymupdf not installed — PDF extraction disabled. Install with: pip install pymupdf")

try:
    from docx import Document as DocxDocument
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False
    logger.warning("python-docx not installed — DOCX extraction disabled. Install with: pip install python-docx")


# Plain text extensions (read as UTF-8)
TEXT_EXTENSIONS = {".txt", ".md", ".csv", ".json", ".log", ".xml", ".yaml", ".yml", ".html", ".htm", ".rst", ".py", ".js", ".ts"}


def extract_text(file_bytes: bytes, filename: str) -> str:
    """Extract text content from a file based on its extension.

    Args:
        file_bytes: Raw file content as bytes.
        filename: Original filename (used to detect format).

    Returns:
        Extracted text content.

    Raises:
        ValueError: If the file format is not supported or extraction fails.
    """
    ext = Path(filename).suffix.lower()

    if ext == ".pdf":
        return _extract_pdf(file_bytes, filename)
    elif ext == ".docx":
        return _extract_docx(file_bytes, filename)
    elif ext in TEXT_EXTENSIONS or not ext:
        return _extract_text(file_bytes, filename)
    else:
        # Try as text, but warn
        logger.warning("unknown_file_extension", filename=filename, extension=ext, fallback="text")
        return _extract_text(file_bytes, filename)


def _extract_pdf(file_bytes: bytes, filename: str) -> str:
    """Extract text from PDF using PyMuPDF."""
    if not PDF_AVAILABLE:
        raise ValueError(
            f"Cannot extract text from PDF '{filename}': pymupdf is not installed. "
            f"Install with: pip install pymupdf"
        )
    try:
        doc = fitz.open(stream=file_bytes, filetype="pdf")
        pages = []
        for page in doc:
            text = page.get_text()
            if text.strip():
                pages.append(text)
        doc.close()

        if not pages:
            raise ValueError(f"PDF '{filename}' contains no extractable text (possibly scanned/image-only).")

        result = "\n\n".join(pages)
        logger.info("pdf_extracted", filename=filename, pages=len(pages), chars=len(result))
        return result
    except ValueError:
        raise
    except Exception as e:
        raise ValueError(f"Failed to extract text from PDF '{filename}': {e}")


def _extract_docx(file_bytes: bytes, filename: str) -> str:
    """Extract text from DOCX using python-docx."""
    if not DOCX_AVAILABLE:
        raise ValueError(
            f"Cannot extract text from DOCX '{filename}': python-docx is not installed. "
            f"Install with: pip install python-docx"
        )
    try:
        doc = DocxDocument(io.BytesIO(file_bytes))
        paragraphs = [p.text for p in doc.paragraphs if p.text.strip()]

        if not paragraphs:
            raise ValueError(f"DOCX '{filename}' contains no text content.")

        result = "\n\n".join(paragraphs)
        logger.info("docx_extracted", filename=filename, paragraphs=len(paragraphs), chars=len(result))
        return result
    except ValueError:
        raise
    except Exception as e:
        raise ValueError(f"Failed to extract text from DOCX '{filename}': {e}")


def _extract_text(file_bytes: bytes, filename: str) -> str:
    """Read file as UTF-8 text."""
    try:
        text = file_bytes.decode("utf-8")
        if not text.strip():
            raise ValueError(f"File '{filename}' is empty or contains only whitespace.")
        logger.info("text_extracted", filename=filename, chars=len(text))
        return text
    except UnicodeDecodeError:
        # Try latin-1 as fallback
        try:
            text = file_bytes.decode("latin-1")
            logger.warning("text_fallback_latin1", filename=filename)
            return text
        except Exception:
            raise ValueError(f"File '{filename}' is not a valid text file (encoding not supported).")


def get_supported_formats() -> dict:
    """Return supported file formats and their availability."""
    return {
        "text": sorted(TEXT_EXTENSIONS),
        "pdf": {".pdf"} if PDF_AVAILABLE else None,
        "docx": {".docx"} if DOCX_AVAILABLE else None,
        "pdf_available": PDF_AVAILABLE,
        "docx_available": DOCX_AVAILABLE,
    }
