"""Model listing service. Auto-generated by ChimerAI CLI."""

import time
import structlog
from typing import Optional

from models import ModelsResponse, ModelInfo
from provider_client import provider_client
from config import settings

logger = structlog.get_logger()

# Fallback models when provider APIs are not reachable
FALLBACK_MODELS = [
    ModelInfo(id="gpt-4", object="model", created=0, owned_by="openai"),
    ModelInfo(id="gpt-4-turbo-preview", object="model", created=0, owned_by="openai"),
    ModelInfo(id="gpt-3.5-turbo", object="model", created=0, owned_by="openai"),
    ModelInfo(id="claude-3-opus-20240229", object="model", created=0, owned_by="anthropic"),
    ModelInfo(id="claude-3-sonnet-20240229", object="model", created=0, owned_by="anthropic"),
    ModelInfo(id="text-embedding-ada-002", object="model", created=0, owned_by="openai"),
]


class ModelService:
    """Service for listing available models with caching."""

    def __init__(self, cache_ttl: int = 300):
        self._cache: Optional[ModelsResponse] = None
        self._cache_time: float = 0
        self._cache_ttl = cache_ttl  # seconds (default 5 min)

    def _is_cache_valid(self) -> bool:
        return self._cache is not None and (time.time() - self._cache_time) < self._cache_ttl

    async def list_models(self) -> ModelsResponse:
        logger.info("list_models_request")

        # Return cached result if valid
        if self._is_cache_valid():
            logger.debug("list_models_cache_hit")
            return self._cache

        try:
            models: list[ModelInfo] = []

            # Try to fetch models from centralized providers
            if await provider_client.is_available():
                providers = await provider_client.get_all_providers()
                for provider in providers:
                    try:
                        # Each provider may expose a list of models
                        if hasattr(provider, "models") and provider.models:
                            for m in provider.models:
                                model_id = m.get("id") or m.get("model_id") if isinstance(m, dict) else str(m)
                                if model_id:
                                    models.append(ModelInfo(
                                        id=model_id,
                                        object="model",
                                        created=int(time.time()),
                                        owned_by=provider.name or "unknown",
                                    ))
                    except Exception as exc:
                        logger.warning("provider_models_error", provider=provider.name, error=str(exc))

            # Try OpenAI API directly as additional source
            if settings.openai_api_key:
                try:
                    from openai import AsyncOpenAI
                    client = AsyncOpenAI(api_key=settings.openai_api_key)
                    openai_models = await client.models.list()
                    for m in openai_models.data:
                        if not any(existing.id == m.id for existing in models):
                            models.append(ModelInfo(
                                id=m.id,
                                object="model",
                                created=m.created or int(time.time()),
                                owned_by=m.owned_by or "openai",
                            ))
                except Exception as exc:
                    logger.warning("openai_models_fetch_error", error=str(exc))

            # Fallback if no dynamic models found
            if not models:
                logger.info("list_models_fallback")
                models = list(FALLBACK_MODELS)

            result = ModelsResponse(object="list", data=models)

            # Cache the result
            self._cache = result
            self._cache_time = time.time()

            logger.info("list_models_success", count=len(models))
            return result

        except Exception as e:
            logger.error("list_models_error", error=str(e))
            # Return fallback on error
            return ModelsResponse(object="list", data=list(FALLBACK_MODELS))


model_service = ModelService()
