"""Content moderation service using OpenAI. Auto-generated by ChimerAI CLI."""

import uuid
from typing import Optional
from openai import AsyncOpenAI
import structlog

from models import (
    ModerationRequest,
    ModerationResponse,
    ModerationResult,
    ModerationCategories,
    ModerationScores,
)
from config import settings
from provider_client import provider_client

logger = structlog.get_logger()


class ModerationService:
    """Content moderation using OpenAI moderation API."""

    async def _get_client(self, provider_id: Optional[str] = None) -> AsyncOpenAI:
        if provider_id:
            provider = await provider_client.get_provider(provider_id)
            if provider and provider.api_key:
                return AsyncOpenAI(api_key=provider.api_key)

        if await provider_client.is_available():
            default = await provider_client.get_default_provider("openai")
            if default and default.api_key:
                return AsyncOpenAI(api_key=default.api_key)

        api_key = settings.openai_api_key
        if not api_key:
            raise ValueError(
                "No OpenAI API key available for moderation. "
                "Configure an OpenAI provider at /providers or set OPENAI_API_KEY."
            )
        return AsyncOpenAI(api_key=api_key)

    async def moderate_content(
        self,
        request: ModerationRequest,
        provider_id: Optional[str] = None,
        user_id: Optional[str] = None,
    ) -> ModerationResponse:
        logger.info("moderation_request", model=request.model)

        try:
            client = await self._get_client(provider_id=provider_id)

            if isinstance(request.input, str):
                inputs = [request.input]
            else:
                inputs = request.input

            response = await client.moderations.create(
                input=inputs,
                model=request.model or "omni-moderation-latest",
            )

            results = []
            for result in response.results:
                results.append(
                    ModerationResult(
                        flagged=result.flagged,
                        categories=ModerationCategories(
                            hate=result.categories.hate,
                            hate_threatening=result.categories.hate_threatening,
                            harassment=result.categories.harassment,
                            harassment_threatening=result.categories.harassment_threatening,
                            self_harm=result.categories.self_harm,
                            self_harm_intent=result.categories.self_harm_intent,
                            self_harm_instructions=result.categories.self_harm_instructions,
                            sexual=result.categories.sexual,
                            sexual_minors=result.categories.sexual_minors,
                            violence=result.categories.violence,
                            violence_graphic=result.categories.violence_graphic,
                        ),
                        category_scores=ModerationScores(
                            hate=result.category_scores.hate,
                            hate_threatening=result.category_scores.hate_threatening,
                            harassment=result.category_scores.harassment,
                            harassment_threatening=result.category_scores.harassment_threatening,
                            self_harm=result.category_scores.self_harm,
                            self_harm_intent=result.category_scores.self_harm_intent,
                            self_harm_instructions=result.category_scores.self_harm_instructions,
                            sexual=result.category_scores.sexual,
                            sexual_minors=result.category_scores.sexual_minors,
                            violence=result.category_scores.violence,
                            violence_graphic=result.category_scores.violence_graphic,
                        ),
                    )
                )

            return ModerationResponse(
                id=f"modr-{uuid.uuid4().hex[:8]}",
                model=request.model or "omni-moderation-latest",
                results=results,
            )

        except ValueError:
            raise
        except Exception as e:
            logger.error("moderation_error", error=str(e))
            raise


moderation_service = ModerationService()
