"""RAG (Retrieval Augmented Generation) service. Auto-generated by ChimerAI CLI."""

from typing import List, Optional
import structlog

from config import settings
from services import vector_store as _vs_module
from services.vector_store import FAISS_AVAILABLE


def _get_vector_store():
    return _vs_module.vector_store
from services.chat_service import chat_service
from models import ChatCompletionRequest, ChatMessage, MessageRole

logger = structlog.get_logger()


class RAGService:
    """Service for Retrieval Augmented Generation (RAG)."""

    def _check_availability(self):
        if not FAISS_AVAILABLE or _get_vector_store() is None:
            raise RuntimeError(
                "FAISS vector store is not available. "
                "Install faiss-cpu: pip install faiss-cpu numpy"
            )

    async def add_documents(
        self,
        documents: List[str],
        metadatas: Optional[List[dict]] = None,
    ) -> dict:
        try:
            self._check_availability()
            ids = await _get_vector_store().add_texts(documents, metadatas)
            logger.info("documents_added", count=len(ids))
            return {
                "status": "success",
                "added": len(ids),
                "ids": ids,
                "total_vectors": _get_vector_store().get_stats()["total_vectors"],
            }
        except Exception as e:
            logger.error("add_documents_failed", error=repr(e))
            raise

    async def search_documents(self, query: str, k: int = 4) -> List[dict]:
        try:
            self._check_availability()
            results = await _get_vector_store().similarity_search(query, k=k)
            logger.info("documents_searched", query_length=len(query), results=len(results))
            return results
        except Exception as e:
            logger.error("search_documents_failed", error=repr(e))
            raise

    async def rag_chat(
        self,
        query: str,
        model: Optional[str] = None,
        k: int = 3,
        temperature: float = 0.7,
        max_tokens: Optional[int] = None,
        provider_id: Optional[str] = None,
        user_id: Optional[str] = None,
        system_prompt: Optional[str] = None,
    ) -> dict:
        try:
            self._check_availability()

            relevant_docs = await _get_vector_store().similarity_search(query, k=k)

            context_parts = []
            for i, doc in enumerate(relevant_docs, 1):
                context_parts.append(f"[Document {i}]\n{doc['text']}")

            context = "\n\n".join(context_parts) if context_parts else "No relevant documents found."

            base_instructions = system_prompt or "You are a helpful assistant. Use the following context to answer the user's question.\nIf the context doesn't contain relevant information, say so and provide a general answer."

            system_message = f"""{base_instructions}

Context:
{context}"""

            messages = [
                ChatMessage(role=MessageRole.SYSTEM, content=system_message),
                ChatMessage(role=MessageRole.USER, content=query),
            ]

            model = model or settings.resolved_chat_model

            chat_request = ChatCompletionRequest(
                model=model,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
            )
            response = await chat_service.create_completion(
                chat_request,
                provider_id=provider_id,
                user_id=user_id,
            )

            response_dict = response.model_dump()

            response_dict["rag_metadata"] = {
                "retrieved_documents": len(relevant_docs),
                "documents": [
                    {
                        "text": doc["text"][:200] + "..." if len(doc["text"]) > 200 else doc["text"],
                        "score": doc["score"],
                        "metadata": doc.get("metadata", {}),
                    }
                    for doc in relevant_docs
                ],
            }

            logger.info("rag_chat_completed", query_length=len(query), docs_retrieved=len(relevant_docs))
            return response_dict

        except Exception as e:
            logger.error("rag_chat_failed", error=repr(e))
            raise

    def get_stats(self) -> dict:
        self._check_availability()
        return _get_vector_store().get_stats()

    def list_documents(self) -> List[dict]:
        self._check_availability()
        return _get_vector_store().list_documents()

    def clear_store(self):
        self._check_availability()
        _get_vector_store().clear()
        return {"status": "success", "message": "Vector store cleared"}

    async def delete_documents(self, document_ids: List[int]) -> dict:
        try:
            self._check_availability()
            deleted = await _get_vector_store().delete_by_ids(document_ids)
            logger.info("documents_deleted", requested=len(document_ids), deleted=deleted)
            return {
                "status": "success",
                "deleted": deleted,
                "remaining_vectors": _get_vector_store().get_stats()["total_vectors"],
            }
        except Exception as e:
            logger.error("delete_documents_failed", error=repr(e))
            raise


rag_service = RAGService()
