"""FAISS-based vector store with chunking and LiteLLM embeddings. Auto-generated by ChimerAI CLI."""

# WARNING: This FAISS index is not user-scoped.
# All users share the same vector store — not suitable for multi-tenant production.
# See https://demo.chimerai.dev/docs/rag-production for isolation options.

try:
    import faiss
    import numpy as np
    FAISS_AVAILABLE = True
except Exception as e:
    FAISS_AVAILABLE = False
    print(f"Warning: FAISS/Numpy not available: {e}")

import pickle
import os
from typing import List, Dict, Any, Optional
import httpx
import litellm
from langchain_text_splitters import RecursiveCharacterTextSplitter
from config import settings
import structlog

logger = structlog.get_logger()


class VectorStore:
    """FAISS-based vector store for document embeddings and semantic search."""

    def __init__(self, dimension: int = 1536, index_path: str = "data/faiss_index"):
        if not FAISS_AVAILABLE:
            raise RuntimeError("FAISS is not available. Please install faiss-cpu.")

        self.dimension = dimension
        self.index_path = index_path
        self.metadata_path = f"{index_path}.metadata.pkl"

        # Text splitter for chunking
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1000,
            chunk_overlap=200,
            length_function=len,
            separators=["\n\n", "\n", ". ", " ", ""],
        )

        self.index = None
        self.metadata: List[Dict[str, Any]] = []
        self._load_or_create_index()

    def _load_or_create_index(self):
        if os.path.exists(self.index_path) and os.path.exists(self.metadata_path):
            try:
                self.index = faiss.read_index(self.index_path)
                with open(self.metadata_path, "rb") as f:
                    self.metadata = pickle.load(f)
                logger.info("faiss_index_loaded", num_vectors=self.index.ntotal)
            except Exception as e:
                logger.error("faiss_index_load_failed", error=repr(e))
                self._create_new_index()
        else:
            self._create_new_index()

    def _create_new_index(self):
        self.index = faiss.IndexFlatL2(self.dimension)
        self.metadata = []
        logger.info("faiss_index_created", dimension=self.dimension)

    def save(self):
        try:
            os.makedirs(os.path.dirname(self.index_path), exist_ok=True)
            faiss.write_index(self.index, self.index_path)
            with open(self.metadata_path, "wb") as f:
                pickle.dump(self.metadata, f)
            logger.info("faiss_index_saved", num_vectors=self.index.ntotal)
        except Exception as e:
            logger.error("faiss_index_save_failed", error=repr(e))
            raise

    async def add_texts(
        self, texts: List[str], metadatas: Optional[List[Dict[str, Any]]] = None
    ) -> List[int]:
        if not texts:
            return []

        if metadatas is None:
            metadatas = [{} for _ in texts]

        # Split texts into chunks
        all_chunks: List[str] = []
        all_metadatas: List[Dict[str, Any]] = []

        for i, text in enumerate(texts):
            chunks = self.text_splitter.split_text(text)
            if not chunks:
                chunks = [text]

            meta = metadatas[i] if i < len(metadatas) else {}
            for j, chunk in enumerate(chunks):
                all_chunks.append(chunk)
                all_metadatas.append({
                    **meta,
                    "_chunk_index": j,
                    "_chunk_total": len(chunks),
                    "_source_doc_index": i,
                })

        embeddings = await self._generate_embeddings(all_chunks)
        embeddings_array = np.array(embeddings, dtype=np.float32)

        start_id = len(self.metadata)
        self.index.add(embeddings_array)

        for k, (chunk, metadata) in enumerate(zip(all_chunks, all_metadatas)):
            self.metadata.append({"_system_id": start_id + k, "_system_text": chunk, **metadata})

        self.save()
        ids = list(range(start_id, start_id + len(all_chunks)))
        logger.info("texts_added_to_index",
                    documents=len(texts),
                    chunks=len(all_chunks),
                    total=self.index.ntotal)
        return ids

    async def delete_by_ids(self, ids: List[int]) -> int:
        ids_set = set(ids)
        remaining = [m for m in self.metadata if m["_system_id"] not in ids_set]

        if len(remaining) == len(self.metadata):
            return 0

        deleted_count = len(self.metadata) - len(remaining)

        self._create_new_index()
        if remaining:
            texts = [m["_system_text"] for m in remaining]
            embeddings = await self._generate_embeddings(texts)
            embeddings_array = np.array(embeddings, dtype=np.float32)
            self.index.add(embeddings_array)
            self.metadata = []
            for k, m in enumerate(remaining):
                new_meta = {key: val for key, val in m.items() if key != "_system_id"}
                new_meta["_system_id"] = k
                self.metadata.append(new_meta)

        self.save()
        logger.info("documents_deleted", deleted=deleted_count, remaining=self.index.ntotal)
        return deleted_count

    async def similarity_search(self, query: str, k: int = 4) -> List[Dict[str, Any]]:
        if self.index.ntotal == 0:
            return []

        query_embeddings = await self._generate_embeddings([query])
        query_vector = np.array(query_embeddings, dtype=np.float32)

        k = min(k, self.index.ntotal)
        distances, indices = self.index.search(query_vector, k)

        results = []
        for i, (distance, idx) in enumerate(zip(distances[0], indices[0])):
            if idx < len(self.metadata):
                stored = self.metadata[idx]
                doc_id = stored.get("_system_id", idx)
                text = stored.get("_system_text", "")
                user_metadata = {
                    k: v for k, v in stored.items() if not k.startswith("_system_")
                }
                similarity_score = 1.0 / (1.0 + float(distance))
                if similarity_score < settings.rag_min_score:
                    continue
                results.append({
                    "id": doc_id,
                    "text": text,
                    "score": similarity_score,
                    "rank": len(results) + 1,
                    "metadata": user_metadata,
                })

        return results

    async def _generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """Embed texts in batches so a single request never has to carry an
        entire large document — that's what was blowing past the timeout.

        NOTE: texts are embedded as-is, with no task prefix. Some models (e.g.
        nomic-embed-text) expect "search_document: "/"search_query: " prefixes
        for best retrieval quality — omitting them is fine for a starter kit,
        but it compresses similarity scores (unrelated text can still score
        ~60%+), so RAG_MIN_SCORE needs empirical tuning rather than an assumed
        universal threshold. See rag-production notes for details."""
        batch_size = max(1, settings.embedding_batch_size)
        embeddings: List[List[float]] = []
        for i in range(0, len(texts), batch_size):
            batch = texts[i:i + batch_size]
            embeddings.extend(await self._embed_batch(batch))
        return embeddings

    async def _embed_batch(self, texts: List[str]) -> List[List[float]]:
        try:
            model = settings.resolved_embedding_model
            is_ollama = model.startswith("ollama/") or model.startswith("ollama_chat/")
            timeout = settings.embedding_timeout_seconds

            if is_ollama:
                # Use Ollama's /api/embed endpoint directly (supports array input)
                model_name = model.split("/", 1)[1]  # strip "ollama/" prefix
                base_url = settings.ollama_base_url.rstrip("/")
                async with httpx.AsyncClient(timeout=timeout) as client:
                    resp = await client.post(
                        f"{base_url}/api/embed",
                        json={"model": model_name, "input": texts},
                    )
                    resp.raise_for_status()
                    data = resp.json()
                    embeddings = data.get("embeddings") or data.get("embedding")
                    if embeddings is None:
                        raise ValueError(f"Unexpected Ollama embed response: {data}")
                    # /api/embed always returns a list of vectors
                    if isinstance(embeddings[0], (int, float)):
                        embeddings = [embeddings]  # single vector → wrap
                logger.info("embeddings_generated", count=len(embeddings), model=model)
                return embeddings

            # Non-Ollama: use LiteLLM
            response = await litellm.aembedding(
                model=model,
                input=texts,
                timeout=timeout,
            )
            embeddings = [
                item["embedding"] if isinstance(item, dict) else item.embedding
                for item in response.data
            ]
            logger.info("embeddings_generated",
                        count=len(embeddings),
                        model=settings.resolved_embedding_model)
            return embeddings
        except Exception as e:
            logger.error("embedding_generation_failed", error=repr(e), batch_size=len(texts))
            raise

    def get_stats(self) -> Dict[str, Any]:
        return {
            "total_vectors": self.index.ntotal,
            "dimension": self.dimension,
            "index_type": type(self.index).__name__,
            "metadata_count": len(self.metadata),
        }

    def list_documents(self) -> List[Dict[str, Any]]:
        """Group stored chunks by filename so the UI can show a document-level
        list. Derived entirely from chunk metadata — there is no separate
        document registry, so uploads sharing a filename are grouped together."""
        groups: Dict[str, Dict[str, Any]] = {}
        for m in self.metadata:
            filename = m.get("filename", "unknown")
            group = groups.setdefault(filename, {
                "filename": filename,
                "content_type": m.get("content_type"),
                "chunk_ids": [],
            })
            group["chunk_ids"].append(m["_system_id"])

        return [
            {**group, "chunk_count": len(group["chunk_ids"])}
            for group in groups.values()
        ]

    def clear(self):
        self._create_new_index()
        self.save()
        logger.info("faiss_index_cleared")


# Initialized lazily at startup via init_vector_store()
vector_store: Optional["VectorStore"] = None


def init_vector_store(dimension: int) -> Optional["VectorStore"]:
    """Initialize (or re-initialize) the global vector store with the given dimension.

    If an existing FAISS index has a different dimension it is automatically
    cleared and rebuilt — no manual file deletion required.
    """
    global vector_store

    if not FAISS_AVAILABLE:
        logger.warning("faiss_not_available_skipping_vector_store")
        return None

    try:
        instance = VectorStore(dimension=dimension)

        # Dimension mismatch: existing index was built with a different model
        if instance.index is not None and instance.index.d != dimension:
            logger.warning(
                "embedding_dimension_mismatch",
                index_dimension=instance.index.d,
                model_dimension=dimension,
                action="clearing_index",
            )
            instance._create_new_index()
            instance.save()

        vector_store = instance
        logger.info("vector_store_initialized", dimension=dimension)
        return vector_store
    except Exception as e:
        logger.error("vector_store_init_failed", error=repr(e))
        return None
