"""Chat API Routes — Auto-generated by ChimerAI CLI."""

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
import structlog

from models import (
    ChatCompletionRequest,
    ChatCompletionResponse,
    ModelsResponse,
    ModerationRequest,
    ModerationResponse,
)
from services.chat_service import chat_service
from services.model_service import model_service
from services.moderation_service import moderation_service

logger = structlog.get_logger()

router = APIRouter(prefix="/api", tags=["chat"])


@router.post("/chat", response_model=ChatCompletionResponse)
async def chat_completion(request: ChatCompletionRequest):
    """Non-streaming chat completion."""
    try:
        return await chat_service.create_completion(
            request,
            provider_id=request.provider_id,
            user_id=request.user_id,
        )
    except Exception as e:
        logger.error("chat_completion_error", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/chat/stream")
async def chat_stream(request: ChatCompletionRequest):
    """Streaming chat completion via SSE."""
    return StreamingResponse(
        chat_service.create_streaming_completion(
            request,
            provider_id=request.provider_id,
            user_id=request.user_id,
        ),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.get("/models", response_model=ModelsResponse)
async def list_models():
    """List available AI models."""
    try:
        return await model_service.list_models()
    except Exception as e:
        logger.error("list_models_error", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/moderate", response_model=ModerationResponse)
async def moderate_content(request: ModerationRequest):
    """Content moderation check."""
    try:
        return await moderation_service.moderate_content(
            request,
            provider_id=request.provider_id,
            user_id=request.user_id,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.error("moderation_error", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))
