"""RAG API Routes — Auto-generated by ChimerAI CLI."""

from typing import List, Optional
from fastapi import APIRouter, HTTPException, UploadFile, File, Form
import structlog

from models import (
    AddDocumentsRequest,
    SearchRequest,
    RAGChatRequest,
    EmbeddingRequest,
    EmbeddingResponse,
    SearchResponse,
    VectorStoreStats,
    DeleteDocumentsRequest,
    DeleteDocumentsResponse,
)
from services.rag_service import rag_service
from services.embedding_service import embedding_service
from services.file_extractor import extract_text, get_supported_formats

logger = structlog.get_logger()

router = APIRouter(prefix="/api", tags=["rag"])


@router.post("/rag/upload")
async def upload_files(files: List[UploadFile] = File(...)):
    """Upload files (PDF, DOCX, TXT, MD, etc.) to the vector store.

    Files are automatically parsed — text is extracted from PDF/DOCX,
    other files are read as UTF-8 text. Each file is chunked and embedded.
    """
    try:
        total_added = 0
        all_ids = []
        results = []

        for file in files:
            try:
                file_bytes = await file.read()
                filename = file.filename or "unknown.txt"
                text = extract_text(file_bytes, filename)

                result = await rag_service.add_documents(
                    documents=[text],
                    metadatas=[{"filename": filename, "content_type": file.content_type or "unknown"}],
                )
                total_added += result["added"]
                all_ids.extend(result["ids"])
                results.append({
                    "filename": filename,
                    "status": "success",
                    "chunks": result["added"],
                    "chunk_ids": result["ids"],
                })
                logger.info("file_uploaded", filename=filename, chunks=result["added"])
            except ValueError as ve:
                results.append({
                    "filename": file.filename or "unknown",
                    "status": "error",
                    "error": str(ve),
                })
                logger.warning("file_upload_failed", filename=file.filename, error=str(ve))
            except Exception as e:
                # Some exceptions (e.g. httpx timeouts) stringify to "" — fall back
                # to the exception type so the user always sees something actionable.
                user_message = str(e) or f"{type(e).__name__} (see server logs for details)"
                results.append({
                    "filename": file.filename or "unknown",
                    "status": "error",
                    "error": user_message,
                })
                logger.error("file_upload_error", filename=file.filename, error=repr(e))

        return {
            "status": "success" if total_added > 0 else "error",
            "added": total_added,
            "ids": all_ids,
            "total_vectors": rag_service.get_stats()["total_vectors"],
            "files": results,
        }
    except Exception as e:
        logger.error("upload_files_error", error=repr(e))
        raise HTTPException(status_code=500, detail=str(e) or repr(e))


@router.get("/rag/formats")
async def supported_formats():
    """List supported file formats for upload."""
    return get_supported_formats()


@router.post("/rag/documents")
async def add_documents(request: AddDocumentsRequest):
    """Add documents to the vector store (JSON/text — for programmatic use)."""
    try:
        result = await rag_service.add_documents(request.documents, request.metadatas)
        return result
    except Exception as e:
        logger.error("add_documents_error", error=repr(e))
        raise HTTPException(status_code=500, detail=str(e) or repr(e))


@router.post("/rag/search", response_model=SearchResponse)
async def search_documents(request: SearchRequest):
    """Similarity search in vector store."""
    try:
        results = await rag_service.search_documents(request.query, request.k)
        return {"results": results, "query": request.query}
    except Exception as e:
        logger.error("search_documents_error", error=repr(e))
        raise HTTPException(status_code=500, detail=str(e) or repr(e))


@router.post("/rag/chat")
async def rag_chat(request: RAGChatRequest):
    """RAG-augmented chat completion."""
    try:
        response = await rag_service.rag_chat(
            query=request.query,
            model=request.model,
            k=request.k,
            temperature=request.temperature,
            max_tokens=request.max_tokens,
            provider_id=request.provider_id,
            user_id=request.user_id,
            system_prompt=request.system_prompt,
        )
        return response
    except Exception as e:
        logger.error("rag_chat_error", error=repr(e))
        raise HTTPException(status_code=500, detail=str(e) or repr(e))


@router.get("/rag/documents")
async def list_documents():
    """List uploaded documents, grouped by filename from chunk metadata.

    There is no separate document registry — this is derived from the FAISS
    chunk metadata, so it survives restarts but groups purely by filename.
    """
    try:
        return {"documents": rag_service.list_documents()}
    except Exception as e:
        logger.error("list_documents_error", error=repr(e))
        raise HTTPException(status_code=500, detail=str(e) or repr(e))


@router.get("/rag/stats", response_model=VectorStoreStats)
async def rag_stats():
    """Vector store statistics."""
    try:
        return rag_service.get_stats()
    except Exception as e:
        logger.error("get_stats_error", error=repr(e))
        raise HTTPException(status_code=500, detail=str(e) or repr(e))


@router.delete("/rag/clear")
async def clear_rag():
    """Clear all documents from vector store."""
    try:
        return rag_service.clear_store()
    except Exception as e:
        logger.error("clear_store_error", error=repr(e))
        raise HTTPException(status_code=500, detail=str(e) or repr(e))


@router.delete("/rag/delete", response_model=DeleteDocumentsResponse)
async def delete_documents(request: DeleteDocumentsRequest):
    """Delete specific documents from vector store by ID."""
    try:
        result = await rag_service.delete_documents(request.document_ids)
        return result
    except Exception as e:
        logger.error("delete_documents_error", error=repr(e))
        raise HTTPException(status_code=500, detail=str(e) or repr(e))


@router.post("/embeddings", response_model=EmbeddingResponse)
async def create_embeddings(request: EmbeddingRequest):
    """Generate embeddings."""
    try:
        return await embedding_service.create_embeddings(
            request,
            provider_id=request.provider_id,
            user_id=request.user_id,
        )
    except Exception as e:
        logger.error("embeddings_error", error=repr(e))
        raise HTTPException(status_code=500, detail=str(e) or repr(e))
