"""ChimerAI AI Service Configuration. Auto-generated by ChimerAI CLI."""

import os
from pydantic_settings import BaseSettings
from typing import Optional

# Look for .env in services/ai/ first, then fall back to project root
_env_file = ".env" if os.path.exists(".env") else "../../.env"


class Settings(BaseSettings):
    # Service
    host: str = "0.0.0.0"
    port: int = 8002

    # Provider Management (Frontend Internal API)
    frontend_url: str = "http://localhost:3000"
    internal_api_token: Optional[str] = None
    internal_service_token: Optional[str] = None

    # API Keys (Fallback)
    openai_api_key: Optional[str] = None

    # Ollama (local, no API key needed)
    ollama_base_url: str = "http://localhost:11434"

    # Caching
    redis_url: str = "redis://localhost:6379"
    redis_enabled: bool = False

    # RAG Settings
    default_embedding_model: str = "text-embedding-ada-002"
    embedding_dimension: int = 1536
    # Timeout for a single embedding request (seconds). Raise for slow/CPU-bound models.
    embedding_timeout_seconds: float = 120.0
    # Number of chunks embedded per request. Smaller batches keep each request well
    # under the timeout regardless of document size.
    embedding_batch_size: int = 20
    # Minimum similarity score (1 / (1 + L2 distance), range ~0-1) a chunk must reach
    # to be used as RAG context. Below this, retrieval is treated as "no match found"
    # instead of feeding irrelevant chunks to the chat model. Tune per embedding model.
    rag_min_score: float = 0.65

    # Default Model
    default_chat_model: str = "gpt-3.5-turbo"

    @property
    def resolved_chat_model(self) -> str:
        """Return the chat model with provider prefix.

        If OLLAMA_BASE_URL is set and the model has no provider prefix,
        automatically prepend 'ollama/'.
        """
        model = self.default_chat_model
        known_prefixes = ("ollama/", "ollama_chat/", "openai/", "anthropic/",
                          "azure/", "cohere/", "huggingface/", "together_ai/")
        if not any(model.startswith(p) for p in known_prefixes):
            if self.ollama_base_url:
                return f"ollama/{model}"
        return model

    @property
    def resolved_embedding_model(self) -> str:
        """Return the embedding model with provider prefix.

        If OLLAMA_BASE_URL is set and the model has no provider prefix
        (e.g. 'nomic-embed-text' or 'nomic-embed-text:latest'),
        automatically prepend 'ollama/' so LiteLLM/httpx can route correctly.
        """
        model = self.default_embedding_model
        known_prefixes = ("ollama/", "ollama_chat/", "openai/", "anthropic/",
                          "azure/", "cohere/", "huggingface/", "together_ai/")
        if not any(model.startswith(p) for p in known_prefixes):
            if self.ollama_base_url:
                return f"ollama/{model}"
        return model

    class Config:
        env_file = _env_file
        extra = "ignore"


settings = Settings()
