"""ChimerAI AI Service — Auto-generated by ChimerAI CLI."""

import os
from contextlib import asynccontextmanager
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
import structlog
import uvicorn

from config import settings
from provider_client import provider_client

from routes.chat_routes import router as chat_router
from services.vector_store import init_vector_store
from routes.rag_routes import router as rag_router

structlog.configure(
    processors=[
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer(),
    ]
)

logger = structlog.get_logger()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup and shutdown logic."""
    logger.info("ai_service_starting", port=settings.port)

    # Set OpenAI key as env fallback for LiteLLM
    if settings.openai_api_key:
        os.environ["OPENAI_API_KEY"] = settings.openai_api_key

    # Try to connect to Frontend Internal API for centralized providers
    provider_mode = "env_fallback"
    if settings.internal_api_token:
        try:
            available = await provider_client.is_available()
            if available:
                providers = await provider_client.get_all_providers()
                provider_mode = "centralized"
                logger.info("provider_client_connected", providers_loaded=len(providers))

                default = await provider_client.get_default_provider()
                if default and default.api_key:
                    os.environ["OPENAI_API_KEY"] = default.api_key
                    logger.info("default_provider_set", provider_name=default.name)
            else:
                logger.warning("provider_client_unavailable")
        except Exception as exc:
            logger.warning("provider_client_error", error=str(exc))

    # --- Auto-detect embedding dimension (RAG) ---
    detected_dim = settings.embedding_dimension  # fallback from .env / default
    model = settings.resolved_embedding_model
    embed_kwargs: dict = {}
    if model.startswith("ollama/") or model.startswith("ollama_chat/"):
        embed_kwargs["api_base"] = settings.ollama_base_url

    try:
        is_ollama = model.startswith("ollama/") or model.startswith("ollama_chat/")
        if is_ollama:
            import httpx
            model_name = model.split("/", 1)[1]
            base_url = settings.ollama_base_url.rstrip("/")
            async with httpx.AsyncClient(timeout=30.0) as hx:
                resp = await hx.post(f"{base_url}/api/embed", json={"model": model_name, "input": ["dimension probe"]})
                resp.raise_for_status()
                data = resp.json()
                vec = (data.get("embeddings") or [data.get("embedding")])[0]
                detected_dim = len(vec)
        else:
            import litellm
            test_resp = await litellm.aembedding(model=model, input=["dimension probe"], **embed_kwargs)
            detected_dim = len(test_resp.data[0]["embedding"] if isinstance(test_resp.data[0], dict) else test_resp.data[0].embedding)
        logger.info("embedding_dimension_detected", model=model, dimension=detected_dim)
    except Exception as exc:
        logger.warning("embedding_dimension_detection_failed", model=model, error=str(exc),
                       fallback_dimension=detected_dim)

    settings.embedding_dimension = detected_dim
    init_vector_store(detected_dim)

    logger.info("ai_service_started", provider_mode=provider_mode, embedding_model=model, embedding_dimension=detected_dim)
    yield

    await provider_client.close()
    logger.info("ai_service_stopped")


app = FastAPI(
    title="ChimerAI AI Service",
    version="1.0.0",
    lifespan=lifespan,
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        settings.frontend_url,
        "http://localhost:3000",
        "http://localhost:3001",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Bearer token auth middleware
@app.middleware("http")
async def verify_service_token(request: Request, call_next):
    """Verify INTERNAL_SERVICE_TOKEN on all non-health endpoints."""
    # Skip auth for health check and docs
    if request.url.path in ("/health", "/docs", "/openapi.json"):
        return await call_next(request)

    expected_token = settings.internal_service_token
    if not expected_token:
        # No token configured — skip auth (development mode)
        return await call_next(request)

    auth_header = request.headers.get("authorization", "")
    if not auth_header.startswith("Bearer "):
        return JSONResponse(
            status_code=401,
            content={"detail": "Missing or invalid Authorization header"},
        )

    token = auth_header[7:]
    if token != expected_token:
        return JSONResponse(
            status_code=401,
            content={"detail": "Invalid service token"},
        )

    return await call_next(request)


# Register routers
app.include_router(chat_router)
app.include_router(rag_router)


# Internal endpoints
@app.post("/api/internal/invalidate-cache")
async def invalidate_cache():
    """Cache invalidation webhook from Frontend."""
    provider_client.invalidate_cache()
    return {"status": "ok"}


@app.get("/health")
async def health():
    """Health check endpoint."""
    provider_available = await provider_client.is_available()
    return {
        "status": "healthy",
        "service": "chimerai-ai-service",
        "provider_mode": "centralized" if provider_available else "env_fallback",
    }


if __name__ == "__main__":
    uvicorn.run(app, host=settings.host, port=settings.port, log_level="info")
