"""Pydantic models for the AI Service. Auto-generated by ChimerAI CLI."""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional, Union
from enum import Enum

# ============================================================================
# Chat Models
# ============================================================================

class MessageRole(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"


class ChatMessage(BaseModel):
    role: MessageRole
    content: str


class ChatCompletionRequest(BaseModel):
    model: str
    messages: List[ChatMessage]
    temperature: Optional[float] = 0.7
    max_tokens: Optional[int] = None
    top_p: Optional[float] = 1.0
    frequency_penalty: Optional[float] = 0.0
    presence_penalty: Optional[float] = 0.0
    stream: Optional[bool] = False
    user: Optional[str] = None
    provider_id: Optional[str] = None
    user_id: Optional[str] = None


class ChatCompletionChoice(BaseModel):
    index: int
    message: ChatMessage
    finish_reason: str


class Usage(BaseModel):
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int


class ChatCompletionResponse(BaseModel):
    id: str
    object: str = "chat.completion"
    created: int
    model: str
    choices: List[ChatCompletionChoice]
    usage: Usage


class DeltaMessage(BaseModel):
    role: Optional[MessageRole] = None
    content: Optional[str] = None


class ChatCompletionChunkChoice(BaseModel):
    index: int
    delta: DeltaMessage
    finish_reason: Optional[str] = None


class ChatCompletionChunk(BaseModel):
    id: str
    object: str = "chat.completion.chunk"
    created: int
    model: str
    choices: List[ChatCompletionChunkChoice]


class ModelInfo(BaseModel):
    id: str
    object: str = "model"
    created: int
    owned_by: str


class ModelsResponse(BaseModel):
    object: str = "list"
    data: List[ModelInfo]


class ModerationRequest(BaseModel):
    input: Union[str, List[str]]
    model: Optional[str] = "omni-moderation-latest"
    provider_id: Optional[str] = None
    user_id: Optional[str] = None


class ModerationCategories(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    hate: bool
    hate_threatening: bool = Field(alias="hate/threatening")
    harassment: bool
    harassment_threatening: bool = Field(alias="harassment/threatening")
    self_harm: bool = Field(alias="self-harm")
    self_harm_intent: bool = Field(alias="self-harm/intent")
    self_harm_instructions: bool = Field(alias="self-harm/instructions")
    sexual: bool
    sexual_minors: bool = Field(alias="sexual/minors")
    violence: bool
    violence_graphic: bool = Field(alias="violence/graphic")


class ModerationScores(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    hate: float
    hate_threatening: float = Field(alias="hate/threatening")
    harassment: float
    harassment_threatening: float = Field(alias="harassment/threatening")
    self_harm: float = Field(alias="self-harm")
    self_harm_intent: float = Field(alias="self-harm/intent")
    self_harm_instructions: float = Field(alias="self-harm/instructions")
    sexual: float
    sexual_minors: float = Field(alias="sexual/minors")
    violence: float
    violence_graphic: float = Field(alias="violence/graphic")


class ModerationResult(BaseModel):
    flagged: bool
    categories: ModerationCategories
    category_scores: ModerationScores


class ModerationResponse(BaseModel):
    id: str
    model: str
    results: List[ModerationResult]

# ============================================================================
# Embedding Models
# ============================================================================

class EmbeddingRequest(BaseModel):
    model: str
    input: Union[str, List[str]]
    user: Optional[str] = None
    provider_id: Optional[str] = None
    user_id: Optional[str] = None


class EmbeddingData(BaseModel):
    object: str = "embedding"
    embedding: List[float]
    index: int


class EmbeddingUsage(BaseModel):
    prompt_tokens: int
    total_tokens: int


class EmbeddingResponse(BaseModel):
    object: str = "list"
    data: List[EmbeddingData]
    model: str
    usage: EmbeddingUsage

# ============================================================================
# RAG Models
# ============================================================================

class AddDocumentsRequest(BaseModel):
    documents: List[str]
    metadatas: Optional[List[dict]] = None


class SearchRequest(BaseModel):
    query: str
    k: int = Field(default=4, ge=1, le=20)


class SearchResult(BaseModel):
    id: int
    text: str
    score: float
    rank: int
    metadata: dict = {}


class SearchResponse(BaseModel):
    results: List[SearchResult]
    query: str


class RAGChatRequest(BaseModel):
    query: str
    model: Optional[str] = None
    k: int = Field(default=3, ge=1, le=10)
    temperature: Optional[float] = 0.7
    max_tokens: Optional[int] = None
    provider_id: Optional[str] = None
    user_id: Optional[str] = None
    system_prompt: Optional[str] = None


class VectorStoreStats(BaseModel):
    total_vectors: int
    dimension: int
    index_type: str
    metadata_count: int


class DeleteDocumentsRequest(BaseModel):
    document_ids: List[int]


class DeleteDocumentsResponse(BaseModel):
    status: str
    deleted: int
    remaining_vectors: int
