"""
Provider Client — Centralized provider resolution.
Auto-generated by ChimerAI CLI. Based on chimerai-kickstart monorepo.
"""

import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional
import httpx
import structlog

from config import settings

logger = structlog.get_logger()


@dataclass
class ProviderModel:
    id: str
    name: str


@dataclass
class ProviderInfo:
    id: str
    name: str
    type: str
    api_key: Optional[str] = None
    base_url: Optional[str] = None
    is_default: bool = False
    is_active: bool = True
    models: List[ProviderModel] = field(default_factory=list)


class ProviderClient:
    """
    Client that fetches provider configuration from the Frontend Internal API.

    Caches results for 5 minutes to avoid hitting the Frontend on every request.
    Falls back gracefully to environment-based keys if the Frontend API is
    unavailable (e.g. during local development without the full stack).
    """

    CACHE_TTL = 300  # 5 minutes

    def __init__(self):
        self._client: Optional[httpx.AsyncClient] = None
        self._cache: Dict[str, ProviderInfo] = {}
        self._all_providers: Optional[List[ProviderInfo]] = None
        self._cache_timestamp: float = 0
        self._available: Optional[bool] = None

    @property
    def client(self) -> httpx.AsyncClient:
        if self._client is None or self._client.is_closed:
            self._client = httpx.AsyncClient(
                base_url=settings.frontend_url,
                headers={
                    "Authorization": f"Bearer {settings.internal_api_token}",
                    "Content-Type": "application/json",
                },
                timeout=10.0,
            )
        return self._client

    def _cache_valid(self) -> bool:
        return (time.time() - self._cache_timestamp) < self.CACHE_TTL

    def invalidate_cache(self):
        self._cache.clear()
        self._all_providers = None
        self._cache_timestamp = 0
        self._available = None
        logger.info("provider_cache_invalidated")

    async def is_available(self) -> bool:
        if self._available is not None and self._cache_valid():
            return self._available

        if not settings.internal_api_token:
            self._available = False
            return False

        try:
            resp = await self.client.get("/api/internal/providers")
            self._available = resp.status_code == 200
        except Exception:
            self._available = False

        return self._available

    async def get_all_providers(self) -> List[ProviderInfo]:
        if self._all_providers is not None and self._cache_valid():
            return self._all_providers

        try:
            resp = await self.client.get("/api/internal/providers")
            resp.raise_for_status()
            data = resp.json()

            providers = []
            for p in data:
                provider = ProviderInfo(
                    id=p["id"],
                    name=p["name"],
                    type=p.get("type", "openai"),
                    api_key=p.get("apiKey") or p.get("api_key"),
                    base_url=p.get("baseUrl") or p.get("base_url"),
                    is_default=p.get("isDefault", False),
                    is_active=p.get("isActive", True),
                    models=[
                        ProviderModel(id=m["id"], name=m["name"])
                        for m in p.get("models", [])
                    ],
                )
                providers.append(provider)
                self._cache[provider.id] = provider

            self._all_providers = providers
            self._cache_timestamp = time.time()
            logger.info("providers_loaded", count=len(providers))
            return providers

        except Exception as e:
            logger.warning("get_providers_failed", error=str(e))
            return self._all_providers or []

    async def get_provider(self, provider_id: str) -> Optional[ProviderInfo]:
        if provider_id in self._cache and self._cache_valid():
            return self._cache[provider_id]

        try:
            resp = await self.client.get(f"/api/internal/providers/{provider_id}")
            resp.raise_for_status()
            p = resp.json()

            provider = ProviderInfo(
                id=p["id"],
                name=p["name"],
                type=p.get("type", "openai"),
                api_key=p.get("apiKey") or p.get("api_key"),
                base_url=p.get("baseUrl") or p.get("base_url"),
                is_default=p.get("isDefault", False),
                is_active=p.get("isActive", True),
            )
            self._cache[provider_id] = provider
            self._cache_timestamp = time.time()
            return provider

        except Exception as e:
            logger.warning("get_provider_failed", provider_id=provider_id, error=str(e))
            return self._cache.get(provider_id)

    async def get_default_provider(self, provider_type: Optional[str] = None) -> Optional[ProviderInfo]:
        providers = await self.get_all_providers()
        for p in providers:
            if p.is_default and p.is_active:
                if provider_type is None or p.type == provider_type:
                    return p
        active = [p for p in providers if p.is_active]
        if provider_type:
            active = [p for p in active if p.type == provider_type]
        return active[0] if active else None

    async def get_api_key(self, provider_id: str) -> Optional[str]:
        provider = await self.get_provider(provider_id)
        return provider.api_key if provider else None

    async def report_usage(
        self,
        provider_id: str,
        user_id: str,
        model: str,
        prompt_tokens: int,
        completion_tokens: int,
        endpoint: str = "/api/chat",
    ) -> None:
        try:
            await self.client.post(
                f"/api/internal/providers/{provider_id}/usage",
                json={
                    "userId": user_id,
                    "model": model,
                    "promptTokens": prompt_tokens,
                    "completionTokens": completion_tokens,
                    "endpoint": endpoint,
                },
            )
        except Exception as e:
            logger.warning("report_usage_failed", error=str(e))

    async def close(self):
        if self._client and not self._client.is_closed:
            await self._client.aclose()
            logger.info("provider_client_closed")


provider_client = ProviderClient()
